### PR TITLE
lang edits (careful merging w/upstream comments)

### PR DESCRIPTION
**Pull request by bumblefudge**
lol not sure whether the github bot will allow my usage of 
```
[link text][linkname]

[linkname]: linkurl
```
syntax, I thought that was standard markdown? maybe it's esoteric linux-dood markdown.  i might need to work with the EIP editors on this next week, if so...

### CODE REVIEW

**Comment by bumblefudge** [comment]
image
😭

**Comment by kdenhartog** [comment]
I believe this just needs to be merged in for it to work: https://github.com/ethereum/eipw/commit/3f4e02593f5111d9b015838b9b8fc74241bc1a96

The syntax shouldn't make a difference here as I already went through and updated the linking in eipw bot in the past because the alternative markdown linking wasn't catching some of these cases in the past.

**Comment by bumblefudge** [comment]
it might be worth merging for the rephrasings and dealing with the link stuff later, since the other implementers are [re-]reading today, it seems...

**Comment by bumblefudge** [comment]
(assuming they're good! feel free to just cherry pick changes and ignore the PR)

**Comment by kdenhartog** [comment]
Yeah I just merged them all in. For some reason GH failed the first time I tried, but a page reload fixed it.

**Pull request merged**
